services:
  db:
    image: postgres:16
    container_name: cctv_os_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
  backend:
    build:
      context: ./backend
    container_name: cctv_os_backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: