# Generated by Django 5.2 on 2026-05-25 19:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Client'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('helper_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('accessories_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fuel_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('lorex', 'Lorex'), ('reolink', 'Reolink'), ('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('axis', 'Axis'), ('hanwha', 'Hanwha'), ('uniview', 'Uniview'), ('other', 'Other')], default='other', max_length=20)),
                ('system_type', models.CharField(choices=[('ip', 'IP / Network'), ('analog', 'Analog / HD')], default='ip', max_length=10)),
                ('camera_shape', models.CharField(choices=[('bullet', 'Bullet'), ('dome', 'Dome'), ('turret', 'Turret'), ('ptz', 'PTZ')], default='bullet', max_length=10)),
                ('camera_color', models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='white', max_length=10)),
                ('connection_type', models.CharField(choices=[('wired', 'Wired'), ('wireless', 'Wireless')], default='wired', max_length=10)),
                ('resolution', models.CharField(blank=True, default='4MP', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
