# Generated by Django 5.2 on 2026-05-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Kitchener', max_length=100)),
                ('province', models.CharField(default='ON', max_length=50)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('lead_source', models.CharField(choices=[('referral', 'Referral'), ('google', 'Google'), ('facebook', 'Facebook'), ('kijiji', 'Kijiji'), ('returning', 'Returning Customer'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote_sent', 'Quote Sent'), ('follow_up', 'Follow Up'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
