# Generated by Django 5.2 on 2026-05-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="Store or location name e.g. 'Downtown Branch', 'Main Office'", max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Kitchener', max_length=100)),
                ('province', models.CharField(default='ON', max_length=50)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('contact_name', models.CharField(blank=True, default='', help_text='On-site contact person if different from main client', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'name'],
            },
        ),
    ]
