# Generated by Django 5.2 on 2026-05-27 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="e.g. 'Main NVR', 'Outdoor DVR', 'Back Camera System'", max_length=255)),
                ('device_id', models.CharField(blank=True, default='', help_text='Serial number or device ID', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=100)),
                ('camera_type', models.CharField(choices=[('ip', 'IP / Network'), ('analog', 'Analog / HD'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('client_port', models.CharField(blank=True, default='', help_text='e.g. 8080, 554, 80', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='clients.client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='clients.location')),
            ],
            options={
                'ordering': ['location', 'device_name'],
            },
        ),
    ]
