# Generated by Django 5.2 on 2026-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
