# Generated by Django 5.2 on 2026-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address'),
        ('clients', '0003_cctvsystem'),
    ]

    operations = [
    ]
