# Generated by Django 5.2 on 2026-05-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_location'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Which client location this job is at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='clients.location'),
        ),
    ]
